let db={tpls:[]},uDB={},u=null,cf=null,ed,lnT,isL=1;
async function init(){ed=document.getElementById('je');lnT=document.getElementById('ln');try{let r=await fetch('data.json');db=await r.json()}catch(e){}let d=localStorage.getItem('bnn_udb');if(d)uDB=JSON.parse(d);chk()}
function tB64(f){return new Promise((r,j)=>{let rd=new FileReader();rd.onload=()=>r(rd.result);rd.onerror=j;rd.readAsDataURL(f)})}
function tTxt(f){return new Promise((r,j)=>{let rd=new FileReader();rd.onload=()=>r(rd.result);rd.onerror=j;rd.readAsText(f)})}
function chk(){let c=sessionStorage.getItem('bnn_cur');if(c&&uDB[c]){u=uDB[c];upd();ld(()=>sh('dv'))}else sh('av')}
function togA(){isL=!isL;document.getElementById('su_f').style.display=isL?'none':'block';document.getElementById('atx').innerText=isL?'Sign In':'Sign Up'}
async function auth(){let n=document.getElementById('un').value,p=document.getElementById('pw').value;if(!n||!p)return Swal.fire('Error','Required','error');if(!isL){if(uDB[n])return Swal.fire('Error','User exists','error');let a=document.getElementById('p_av').files[0],b=document.getElementById('p_bg').files[0];u={n:n,p:p,i:a?await tB64(a):'',bg:b?await tB64(b):'',b:document.getElementById('pb').value||'',fs:[]};uDB[n]=u;localStorage.setItem('bnn_udb',JSON.stringify(uDB))}else{if(!uDB[n]||uDB[n].p!==p)return Swal.fire('Error','Invalid credentials','error');u=uDB[n]}sessionStorage.setItem('bnn_cur',n);upd();ld(()=>sh('dv'))}
function ld(cb){sh('lv');setTimeout(()=>{cb()},1200)}
function lo(){sessionStorage.removeItem('bnn_cur');location.reload()}
function upd(){if(!u)return;document.getElementById('dn').innerText=u.n;document.getElementById('di').src=u.i||`https://ui-avatars.com/api/?name=${u.n}&background=random`;document.getElementById('pbio').value=u.b;if(u.bg)document.body.style.backgroundImage=`url(${u.bg})`;else document.body.style.background='#f8fafc';rG()}
async function svP(){let a=document.getElementById('pi_f').files[0],b=document.getElementById('pb_f').files[0];if(a)u.i=await tB64(a);if(b)u.bg=await tB64(b);u.b=document.getElementById('pbio').value;uDB[u.n]=u;localStorage.setItem('bnn_udb',JSON.stringify(uDB));upd();sh('dv');Swal.fire('Synced','Profile stored locally','success')}
function sh(id){document.querySelectorAll('.v').forEach(v=>v.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='dv'){gsap.from("#tg > div, #fg > div",{opacity:0,y:20,stagger:.05,duration:.5,ease:"back.out(1.7)"});document.getElementById('db-foot').style.display='flex'}else{document.getElementById('db-foot').style.display='none'}}
function rG(q=''){let ts=db.tpls.filter(t=>t.name.toLowerCase().includes(q.toLowerCase()));document.getElementById('tg').innerHTML=ts.map(t=>`<div class="card-hover glass rounded-[2rem] p-5 cursor-pointer border border-white/40" onclick='ld(()=>oE(${JSON.stringify(t).replace(/'/g,"&#39;")}))'><img src="${t.thumb||''}" onerror="this.src='https://placehold.co/400?text=TPL'" class="w-full h-32 object-cover rounded-2xl mb-4"><h3 class="text-lg font-black">${t.name}</h3><p class="text-[10px] font-bold text-blue-600 mt-1 uppercase">Template</p></div>`).join('');let fs=(u.fs||[]).filter(f=>f.n.toLowerCase().includes(q.toLowerCase()));document.getElementById('fg').innerHTML=fs.map((f,i)=>`<div class="card-hover glass rounded-2xl p-4 cursor-pointer flex items-center gap-3" onclick='ld(()=>oF(${i}))'><div class="w-10 h-10 rounded-xl bg-slate-900 text-white flex items-center justify-center shrink-0"><i class="fas fa-file"></i></div><div class="overflow-hidden"><h3 class="text-sm font-bold truncate">${f.n}</h3><p class="text-[10px] text-slate-500 uppercase">${f.t.split('/')[1]||f.t}</p></div></div>`).join('')}
function srch(q){rG(q)}
function oE(t){document.getElementById('et').innerText=t.name;ed.value=JSON.stringify(t.config||t,null,4);ed.oninput=sL;sh('ev');sL()}
function sL(){let t=ed.value;lnT.innerHTML=Array(t.split('\n').length).fill(0).map((_,i)=>i+1).join('<br>')}
async function hF(e){let f=e.files[0];if(!f)return;ld(async ()=>{let r=f.type.includes('text')||f.type.includes('json')||f.type.includes('javascript')||f.type.includes('html')||f.type.includes('css')?await tTxt(f):await tB64(f);if(!u.fs)u.fs=[];u.fs.push({n:f.name,t:f.type,s:f.size,d:r});uDB[u.n]=u;localStorage.setItem('bnn_udb',JSON.stringify(uDB));rG();sh('dv');Swal.fire('Stored','File saved to local workspace','success');e.value=''})}
function oF(i){cf=i;let f=u.fs[i],c=document.getElementById('fv_c'),b=document.getElementById('f_sv');document.getElementById('f_nm').innerText=f.n;document.getElementById('f_sz').innerText=(f.s/1024).toFixed(2)+' KB';b.style.display='none';c.innerHTML='';if(f.t.includes('image'))c.innerHTML=`<img src="${f.d}">`;else if(f.t.includes('video'))c.innerHTML=`<video src="${f.d}" controls autoplay></video>`;else if(f.t.includes('audio'))c.innerHTML=`<audio src="${f.d}" controls autoplay></audio>`;else if(f.t.includes('pdf'))c.innerHTML=`<iframe src="${f.d}" class="w-full h-full rounded-2xl bg-white"></iframe>`;else{c.innerHTML=`<textarea id="f_ed" class="w-full h-full bg-transparent text-green-400 font-mono text-sm outline-none resize-none custom-scroll p-4" spellcheck="false"></textarea>`;document.getElementById('f_ed').value=f.d;b.style.display='block'}sh('fv')}
function svF(){let v=document.getElementById('f_ed').value;u.fs[cf].d=v;uDB[u.n]=u;localStorage.setItem('bnn_udb',JSON.stringify(uDB));Swal.fire('Saved','File updated successfully','success')}
async function exp(){let c=ed.value,z=new JSZip();z.file("config.json",c);let b=await z.generateAsync({type:"blob"});saveAs(b,`bnn_export_${Date.now()}.zip`);Swal.fire('Exported','Data bundled successfully','success')}
window.onload=init;