let db={tpls:[]},uDB={},u=null,cf=null,ed,lnT,isL=1;
let nF='none',nB=100,nC=100,nS=100,nBl=0,nHu=0,nR=0,nFH=1,nFV=1,nBr='none';
const fts=[{n:'Normal',f:'none'},{n:'Mono',f:'grayscale(100%)'},{n:'Sepia',f:'sepia(100%)'},{n:'Invert',f:'invert(100%)'},{n:'Cold',f:'hue-rotate(30deg) saturate(120%)'},{n:'Warm',f:'sepia(30%) hue-rotate(-10deg) brightness(110%)'},{n:'Cyber',f:'hue-rotate(140deg) saturate(200%)'},{n:'Noir',f:'grayscale(100%) contrast(160%) brightness(90%)'},{n:'Fade',f:'brightness(110%) opacity(80%) contrast(90%)'},{n:'Vintage',f:'sepia(50%) contrast(120%)'},{n:'Intense',f:'contrast(170%)'},{n:'Dark',f:'brightness(50%)'},{n:'Bright',f:'brightness(150%)'},{n:'Beds',f:'saturate(250%)'},{n:'Blurry',f:'blur(5px)'},{n:'Retro',f:'contrast(110%) sepia(30%) brightness(105%)'},{n:'Solar',f:'hue-rotate(180deg) invert(20%)'},{n:'Aqua',f:'hue-rotate(90deg) saturate(150%)'},{n:'Magma',f:'hue-rotate(-45deg) saturate(180%)'},{n:'Cinema',f:'brightness(90%) contrast(140%)'}];
const bds=[{n:'None',v:'none'},{n:'White',v:'12px solid #fff'},{n:'Onyx',v:'12px solid #111'},{n:'Glow',v:'box-shadow:0 0 25px #3b82f6'},{n:'Gold',v:'10px double #d4af37'},{n:'Dash',v:'4px dashed #64748b'},{n:'Soft',v:'border-radius:2rem'}];
async function init(){ed=document.getElementById('je');lnT=document.getElementById('ln');try{let r=await fetch('data.json');db=await r.json()}catch(e){}let d=localStorage.getItem('bnn_udb');if(d)uDB=JSON.parse(d);chk();bldNP()}
function tB64(f){return new Promise((r,j)=>{let rd=new FileReader();rd.onload=()=>r(rd.result);rd.onerror=j;rd.readAsDataURL(f)})}
function tTxt(f){return new Promise((r,j)=>{let rd=new FileReader();rd.onload=()=>r(rd.result);rd.onerror=j;rd.readAsText(f)})}
function chk(){let c=sessionStorage.getItem('bnn_cur');if(c&&uDB[c]){u=uDB[c];upd();ld(()=>sh('dv'))}else sh('av')}
function togA(){isL=!isL;document.getElementById('su_f').style.display=isL?'none':'block';document.getElementById('atx').innerText=isL?'Sign In':'Sign Up'}
async function auth(){let n=document.getElementById('un').value,p=document.getElementById('pw').value;if(!n||!p)return Swal.fire('Error','Required','error');if(!isL){if(uDB[n])return Swal.fire('Error','User exists','error');let a=document.getElementById('p_av').files[0],b=document.getElementById('p_bg').files[0];u={n:n,p:p,i:a?await tB64(a):'',bg:b?await tB64(b):'',b:document.getElementById('pb').value||'',fs:[]};uDB[n]=u;localStorage.setItem('bnn_udb',JSON.stringify(uDB))}else{if(!uDB[n]||uDB[n].p!==p)return Swal.fire('Error','Invalid credentials','error');u=uDB[n]}sessionStorage.setItem('bnn_cur',n);upd();ld(()=>sh('dv'))}
function ld(cb){sh('lv');setTimeout(()=>{cb()},1200)}
function lo(){sessionStorage.removeItem('bnn_cur');location.reload()}
function upd(){if(!u)return;document.getElementById('dn').innerText=u.n;document.getElementById('di').src=u.i||`https://ui-avatars.com/api/?name=${u.n}&background=random`;document.getElementById('pbio').value=u.b;if(u.bg)document.body.style.backgroundImage=`url(${u.bg})`;else document.body.style.background='#f8fafc';rG()}
async function svP(){let a=document.getElementById('pi_f').files[0],b=document.getElementById('pb_f').files[0];if(a)u.i=await tB64(a);if(b)u.bg=await tB64(b);u.b=document.getElementById('pbio').value;uDB[u.n]=u;localStorage.setItem('bnn_udb',JSON.stringify(uDB));upd();sh('dv');Swal.fire('Synced','Profile stored locally','success')}
function sh(id){document.querySelectorAll('.v').forEach(v=>v.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='dv'){gsap.from("#tg > div, #fg > div",{opacity:0,y:20,stagger:.05,duration:.5,ease:"back.out(1.7)"});document.getElementById('db-foot').style.display='flex'}else{document.getElementById('db-foot').style.display='none'}}
function rG(q=''){let ts=db.tpls.filter(t=>t.name.toLowerCase().includes(q.toLowerCase()));document.getElementById('tg').innerHTML=ts.map(t=>`<div class="card-hover glass rounded-[2rem] p-5 cursor-pointer border border-white/40" onclick='ld(()=>oE(${JSON.stringify(t).replace(/'/g,"&#39;")}))'><img src="${t.thumb||''}" onerror="this.src='https://placehold.co/400?text=TPL'" class="w-full h-32 object-cover rounded-2xl mb-4"><h3 class="text-lg font-black">${t.name}</h3><p class="text-[10px] font-bold text-blue-600 mt-1 uppercase">Template</p></div>`).join('');let fs=(u.fs||[]).filter(f=>f.n.toLowerCase().includes(q.toLowerCase()));document.getElementById('fg').innerHTML=fs.map((f,i)=>`<div class="card-hover glass rounded-2xl p-4 cursor-pointer flex items-center gap-3" onclick='ld(()=>oF(${i}))'><div class="w-10 h-10 rounded-xl bg-slate-900 text-white flex items-center justify-center shrink-0"><i class="fas fa-file"></i></div><div class="overflow-hidden"><h3 class="text-sm font-bold truncate">${f.n}</h3><p class="text-[10px] text-slate-500 uppercase">${f.t.split('/')[1]||f.t}</p></div></div>`).join('')}
function srch(q){rG(q)}
function oE(t){document.getElementById('et').innerText=t.name;ed.value=JSON.stringify(t.config||t,null,4);ed.oninput=sL;sh('ev');sL()}
function sL(){let t=ed.value;lnT.innerHTML=Array(t.split('\n').length).fill(0).map((_,i)=>i+1).join('<br>')}
async function hF(e){let f=e.files[0];if(!f)return;ld(async ()=>{let r=f.type.includes('text')||f.type.includes('json')||f.type.includes('javascript')||f.type.includes('html')||f.type.includes('css')?await tTxt(f):await tB64(f);if(!u.fs)u.fs=[];u.fs.push({n:f.name,t:f.type,s:f.size,d:r});uDB[u.n]=u;localStorage.setItem('bnn_udb',JSON.stringify(uDB));rG();sh('dv');Swal.fire('Stored','File saved to local workspace','success');e.value=''})}
function oF(i){cf=i;let f=u.fs[i],c=document.getElementById('fv_c'),b=document.getElementById('f_sv'),n=document.getElementById('f_np');document.getElementById('f_nm').innerText=f.n;document.getElementById('f_sz').innerText=(f.s/1024).toFixed(2)+' KB';b.style.display='none';n.style.display='none';c.innerHTML='';if(f.t.includes('image')){c.innerHTML=`<img src="${f.d}" id="fv_img_src">`;n.style.display='block'}else if(f.t.includes('video'))c.innerHTML=`<video src="${f.d}" controls autoplay></video>`;else if(f.t.includes('audio'))c.innerHTML=`<audio src="${f.d}" controls autoplay></audio>`;else if(f.t.includes('pdf'))c.innerHTML=`<iframe src="${f.d}" class="w-full h-full rounded-2xl bg-white"></iframe>`;else{c.innerHTML=`<textarea id="f_ed" class="w-full h-full bg-transparent text-green-400 font-mono text-sm outline-none resize-none custom-scroll p-4" spellcheck="false"></textarea>`;document.getElementById('f_ed').value=f.d;b.style.display='block'}sh('fv')}
function svF(){let v=document.getElementById('f_ed').value;u.fs[cf].d=v;uDB[u.n]=u;localStorage.setItem('bnn_udb',JSON.stringify(uDB));Swal.fire('Saved','File updated successfully','success')}
async function exp(){let c=ed.value,z=new JSZip();z.file("config.json",c);let b=await z.generateAsync({type:"blob"});saveAs(b,`bnn_export_${Date.now()}.zip`);Swal.fire('Exported','Data bundled successfully','success')}
function bldNP(){document.getElementById('np-fl').innerHTML=fts.map((f,i)=>`<div class="flex flex-col items-center gap-1 text-[10px] font-black"><img src="https://placehold.co/100?text=${f.n}" class="np-tmb ${i===0?'active':''}" style="filter:${f.f}" onclick="stF_NP(${i},this)"><span class="uppercase tracking-wider text-slate-400">${f.n}</span></div>`).join('');document.getElementById('np-bx').innerHTML=bds.map((b,i)=>`<button onclick="stB_NP(${i})" class="p-2.5 bg-slate-800 rounded-xl font-bold text-[10px] text-center hover:bg-slate-700 truncate uppercase tracking-tighter">${b.n}</button>`).join('')}
function oNP(){let src=document.getElementById('fv_img_src').src;document.getElementById('np-img').src=src;nF='none';nB=100;nC=100;nS=100;nBl=0;nHu=0;nR=0;nFH=1;nFV=1;nBr='none';rNP();sh('nv')}
function updNP(t,v){if(t==='br'){nB=v;document.getElementById('v-br').innerText=v+'%'}if(t==='ct'){nC=v;document.getElementById('v-ct').innerText=v+'%'}if(t==='st'){nS=v;document.getElementById('v-st').innerText=v+'%'}if(t==='bl'){nBl=v;document.getElementById('v-bl').innerText=v+'px'}if(t==='hu'){nHu=v;document.getElementById('v-hu').innerText=v+'°'}rNP()}
function stF_NP(i,e){document.querySelectorAll('.np-tmb').forEach(x=>x.classList.remove('active'));e.classList.add('active');nF=fts[i].f;rNP()}
function stB_NP(i){nBr=bds[i].v;rNP()}
function tfNP(t){if(t==='r')nR=(nR+90)%360;if(t==='h')nFH=nFH===-1?1:-1;if(t==='v')nFV=nFV===-1?1:-1;rNP()}
function rNP(){let img=document.getElementById('np-img'),v=document.getElementById('np-vp');let fl=`brightness(${nB}%) contrast(${nC}%) saturate(${nS}%) blur(${nBl}px) hue-rotate(${nHu}deg)`;if(nF!=='none')fl+=` ${nF}`;img.style.filter=fl;img.style.transform=`rotate(${nR}deg) scale(${nFH},${nFV})`;v.style.border='none';v.style.boxShadow='none';v.style.borderRadius='0px';if(nBr.includes('solid')||nBr.includes('double')){v.style.border=nBr}else if(nBr.includes('box-shadow')){v.style.boxShadow=nBr.split(':')[1]}else if(nBr.includes('radius')){v.style.borderRadius=nBr.split(':')[1]}}
function svNP(){ld(()=>{let img=new Image();img.src=document.getElementById('np-img').src;img.onload=()=>{let cv=document.createElement('canvas'),ctx=cv.getContext('2d');let iw=img.naturalWidth,ih=img.naturalHeight;if(nR%180!==0){cv.width=ih;cv.height=iw}else{cv.width=iw;cv.height=ih}ctx.translate(cv.width/2,cv.height/2);ctx.rotate((nR*Math.PI)/180);ctx.scale(nFH,nFV);let fl=`brightness(${nB}%) contrast(${nC}%) saturate(${nS}%) blur(${nBl}px) hue-rotate(${nHu}deg)`;if(nF!=='none')fl+=` ${nF}`;ctx.filter=fl;ctx.drawImage(img,-iw/2,-ih/2);u.fs[cf].d=cv.toDataURL(u.fs[cf].t);uDB[u.n]=u;localStorage.setItem('bnn_udb',JSON.stringify(uDB));rG();sh('dv');Swal.fire('NAPOSTO Sync','Image rendered and stored successfully','success')}})}
window.onload=init;